//User
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";

//UI
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

//Data
export const SET_MENTIONS = "SET_MENTIONS";
export const SET_MENTION = "SET_MENTION";
export const LIKE_MENTION = "LIKE_MENTION";
export const UNLIKE_MENTION = "UNLIKE_MENTION";
export const DELETE_MENTION = "DELETE_MENTION";
export const POST_MENTION = "POST_MENTION";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
